spring.application.name=tp6-Serveur
server.port=8181

server.http2.enabled=true

# gRPC server configuration
spring.grpc.server.port=9090
spring.grpc.server.address=0.0.0.0

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/