spring.application.name=tp8-config-server
server.port=8888

# Configuration du stockage en mode "Fichier Local" (plus simple pour les étudiants que Git)
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:///C:/Users/Fabrice/Workspaces/WorkspaceIng1/config-repo/

# Liaison à l'annuaire
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
