spring.application.name=tp8-Serveur

server.http2.enabled=true

spring.config.import=optional:configserver:http://localhost:8888

spring.cloud.config.import-check.enabled=true
spring.cloud.config.enabled=true
