spring.application.name=tp5-Client
server.port=8282

# gRPC client configuration
spring.grpc.client.channels.productClient.address=static://127.0.0.1:8181
spring.grpc.client.channels.productClient.secure=false
