spring.application.name=tp9-client

# 1. On donne un port de secours (ex: 8282 ou 0 pour un port aléatoire libre)
# Cela évite le conflit immédiat sur le port 8080 au démarrage de Tomcat
server.port=8282

# 2. On importe la configuration depuis le Config Server
spring.config.import=configserver:http://localhost:8888

spring.cloud.config.import-check.enabled=true
spring.cloud.config.enabled=true