spring.application.name=tp6-Client
server.port=8282

# gRPC client configuration
spring.grpc.client.channels.productClient.secure=false

spring.cloud.config.enabled=false

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/