spring.application.name=tp8-stock

# Cette ligne indique à Spring Boot d'aller chercher la configuration sur le Config Server
spring.config.import=optional:configserver:http://localhost:8888/

# (Optionnel) Si vous utilisez Eureka pour localiser le Config Server
# eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/