spring.application.name=tp8-server

# Au démarrage, le client va chercher ses propriétés sur le serveur de config
spring.config.import=optional:configserver:http://localhost:8888

# On réactive l'import check que l'on avait désactivé au TP6
spring.cloud.config.import-check.enabled=true
spring.cloud.config.enabled=true