services:

  tp9-registry:
    image: tp9-registry:latest
    container_name: tp9-registry
    ports:
      - "9876:8761"
    networks:
      - tp9-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 4s
      timeout: 3s
      retries: 5
    depends_on: []

  tp9-config-server:
    image: tp9-config-server:latest
    container_name: tp9-config-server
    ports:
      - "8888:8888"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://tp9-registry:8761/eureka/
    depends_on:
      tp9-registry:
        condition: service_healthy
    networks:
      - tp9-network
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8888/actuator/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  tp9-server:
    image: tp9-server:latest
    container_name: tp9-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://tp9-registry:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://tp9-config-server:8888/
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/tp9
    depends_on:
      - tp9-config-server
      - mongodb
    networks:
      - tp9-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 10

  mongodb:
    image: mongo:latest
    container_name: tp9-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - tp9-network

  mongo-express:
    image: mongo-express:latest
    container_name: tp9-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongodb
    networks:
      - tp9-network

volumes:
  mongo-data:

networks:
  tp9-network:
    driver: bridge