spring.application.name=tp8-Client
server.port=8282

spring.config.import=configserver:http://localhost:8888

# gRPC client configuration
spring.cloud.config.import-check.enabled=true
spring.cloud.config.enabled=true